# Generated by Django 5.1.3 on 2025-05-30 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_contacts_email_alter_contacts_vebsite_and_more'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionally',
            name='ID_NDS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.nds_info'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_SumDiscountPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_SumNoDiscountPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_discountPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
