# Generated by Django 5.1.3 on 2025-05-27 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_organization_id_privite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='ID_Counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.counterparty'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ID_NDS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.nds_info'),
        ),
        migrations.AlterField(
            model_name='privite_facecounter',
            name='ID_Counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.counterparty'),
        ),
    ]
