# Generated by Django 5.1.3 on 2025-05-27 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_organization_id_counterparty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank_requisites',
            old_name='adress',
            new_name='bank_adress',
        ),
        migrations.RenameField(
            model_name='bank_requisites',
            old_name='name',
            new_name='bank_name',
        ),
        migrations.RenameField(
            model_name='organization_info',
            old_name='name',
            new_name='org_name',
        ),
        migrations.RenameField(
            model_name='privite_face',
            old_name='Adress',
            new_name='priv_adress',
        ),
        migrations.RenameField(
            model_name='privite_face',
            old_name='name',
            new_name='priv_name',
        ),
    ]
