# Generated by Django 5.1.3 on 2025-05-27 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_adress_bank_requisites_bank_adress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization_info',
            old_name='Adress',
            new_name='org_adress',
        ),
    ]
