# Generated by Django 5.1.3 on 2025-05-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_nds_info_nds_alter_nds_info_nds_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='vebsite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='USL_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employers',
            name='name_kass',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization_info',
            name='OKPO_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization_info',
            name='OKVED',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization_info',
            name='all_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization_info',
            name='org_adress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
