# Generated by Django 5.1.3 on 2025-06-11 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=255)),
                ('g_codedig', models.IntegerField()),
                ('g_codename', models.IntegerField()),
                ('g_count', models.IntegerField()),
                ('g_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('g_discount', models.IntegerField(blank=True, null=True)),
                ('g_discountPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('g_SumNoDiscountPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('g_SumDiscountPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Additionally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purpose', models.CharField(max_length=255)),
                ('Payfor', models.CharField(max_length=255)),
                ('Agreement', models.CharField(max_length=255)),
                ('additionally_status', models.CharField(choices=[('checkpech', 'Счет'), ('checkpech1c', 'Счет(1С)'), ('checkpech1cno', 'Счет(1С без лого)'), ('checkip', 'Счет ИП'), ('checkip1c', 'Счет ИП(1С)'), ('checkip1cno', 'Счет ИП(1С без лого)'), ('checkpech1', 'Счет#1'), ('checkpech2', 'Счет#2'), ('checkpech2ip', 'Счет#2 ИП')], max_length=255)),
                ('currency', models.CharField(choices=[('rus', 'Российский рубль'), ('usa', 'Доллар США'), ('eur', 'Евро'), ('byn', 'Белорусский рубль'), ('uah', 'Гривна'), ('kzt', 'Тенге'), ('baht', 'Бат'), ('tmt ', 'Новый туркментский манат')], max_length=255)),
                ('discount_fact', models.BooleanField(default=False)),
                ('discount_size', models.IntegerField(blank=True, null=True)),
                ('ID_NDS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.nds_info')),
            ],
        ),
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee_status', models.IntegerField(choices=[(0, 'Покупатель является грузополучателем'), (1, 'Грузополучатель другая организация')])),
                ('ID_Counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.counterparty')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_num', models.IntegerField(unique=True)),
                ('check_date', models.DateField()),
                ('counter_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.counterparty')),
                ('more_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.additionally')),
                ('org_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
                ('ID_consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.consignee')),
            ],
        ),
        migrations.CreateModel(
            name='CheckForGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.check')),
                ('ID_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.goods')),
            ],
        ),
        migrations.CreateModel(
            name='User_Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.check')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
