# Generated by Django 5.1.3 on 2025-06-01 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignee',
            name='ID_Counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.counterparty'),
        ),
    ]
