# Generated by Django 5.1.3 on 2025-06-01 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_adress', models.CharField(max_length=255)),
                ('KS', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('fax', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vebsite', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('org', 'Organization'), ('ind', 'Individual')], default='org', max_length=10)),
                ('USL_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_boss', models.CharField(max_length=255)),
                ('name_boss', models.CharField(max_length=255)),
                ('name_buh', models.CharField(max_length=255)),
                ('name_kass', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NDS_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nds_stavka', models.IntegerField(blank=True, choices=[(0, 'Без НДС'), (10, '10%'), (18, '18%'), (20, '20%')], null=True)),
                ('nds_status', models.IntegerField(choices=[(1, 'не учитывать'), (2, 'в сумме'), (3, 'Сверху')])),
            ],
        ),
        migrations.CreateModel(
            name='Organization_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('all_name', models.CharField(blank=True, max_length=255, null=True)),
                ('INN_number', models.IntegerField()),
                ('OKPO_code', models.IntegerField(blank=True, null=True)),
                ('OKVED', models.IntegerField(blank=True, null=True)),
                ('org_adress', models.CharField(blank=True, max_length=255, null=True)),
                ('OGRN', models.IntegerField()),
                ('IP_fact', models.BooleanField(default=False)),
                ('KPP', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Privite_face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priv_name', models.CharField(max_length=255)),
                ('priv_adress', models.CharField(max_length=255)),
                ('passport', models.CharField(max_length=255)),
                ('Who_gave', models.CharField(max_length=255)),
                ('DATE_gave', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Counterparty_bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RS', models.IntegerField()),
                ('ID_Counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.counterparty')),
                ('ID_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.bank_requisites')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.counterparty')),
                ('ID_NDS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.nds_info')),
                ('ID_contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.contacts')),
                ('ID_employers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.employers')),
                ('ID_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organization_info')),
                ('ID_privite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.privite_face')),
            ],
        ),
        migrations.CreateModel(
            name='organization_bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RS', models.IntegerField()),
                ('ID_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.bank_requisites')),
                ('ID_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Privite_FaceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.counterparty')),
                ('ID_contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.contacts')),
                ('ID_employers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.employers')),
                ('ID_privite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.privite_face')),
            ],
        ),
        migrations.CreateModel(
            name='User_Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterparty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.counterparty')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
