# Generated by Django 5.1.3 on 2025-05-27 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_privite_facecounter_id_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='ID_privite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.privite_face'),
        ),
    ]
