# Generated by Django 5.1.3 on 2025-05-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_adress_organization_info_org_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nds_info',
            name='NDS',
        ),
        migrations.AlterField(
            model_name='nds_info',
            name='nds_status',
            field=models.IntegerField(choices=[(1, 'не учитывать'), (2, 'в сумме'), (3, 'Сверху')]),
        ),
        migrations.AlterField(
            model_name='nds_info',
            name='nds_stavka',
            field=models.IntegerField(blank=True, choices=[(0, 'Без НДС'), (10, '10%'), (18, '18%'), (20, '20%')], null=True),
        ),
    ]
