# Generated by Django 5.2 on 2025-05-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_contacts_email_alter_contacts_vebsite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='type',
            field=models.CharField(choices=[('org', 'Organization'), ('ind', 'Individual')], default='org', max_length=10),
        ),
    ]
