# Generated by Django 5.2 on 2025-05-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_counterparty_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='type',
            field=models.IntegerField(choices=[('org', 'Organization'), ('ind', 'Individual')]),
        ),
    ]
