# Generated by Django 5.2 on 2025-05-30 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_counterparty_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='type',
            field=models.CharField(choices=[('org', 'Organization'), ('ind', 'Individual')], default='org', max_length=10),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ID_employers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.employers'),
        ),
    ]
